development:
  adapter: postgresql
  encoding: utf8
  database: champ_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  encoding: utf8
  database: champ_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: champ_production
  pool: 5
  timeout: 5000
